### ISSUE TITLE
does plant scene need particles?

### ISSUE THREAD

**Issue by ofZach** [ofZach/funkyForms#4]
I'd like to move particles and springs to be more common since they are used in other scenes.  Are you still using them here ?      Maybe it's good to remove any un-used code

**Comment by GordeyChernyy** [comment]
Yeah, it is a good idea, I did some changes in particles in eye scene, but I can modify it.

**Comment by ofZach** [comment]
one option is to extend the particle and make your own type (eyeParticle) with new methods, etc...
that way it's easy to keep the main type around but not ruin it for other scenes, etc.
